export const LEARNING_TRACKS = [
  {
    id: 'ai-engineering',
    title: 'Applied AI Engineering',
    description: 'Build useful AI workflows with grounding, structured outputs, evaluation, confidence, governance and human control.',
    icon: 'BrainCircuit',
    modules: [
      {
        slug: 'ai-foundations-for-engineers',
        title: 'AI Foundations for Engineers',
        level: 'Foundation',
        duration: '60–90 min',
        summary: 'Understand models, prompts, tokens, context, temperature, structured outputs and where AI systems fail.',
        tags: ['LLMs', 'Prompts', 'Context'],
        outcomes: ['Explain what an LLM is and is not', 'Recognise common failure modes', 'Choose deterministic vs generative behaviour'],
        lessons: [
          { title: 'From deterministic software to probabilistic systems', body: 'Traditional software follows explicit logic. Generative AI predicts outputs from context, so correctness must be evaluated differently.' },
          { title: 'Prompt, context and model responsibilities', body: 'Separate instructions, business context, retrieved evidence and model behaviour so failures can be diagnosed rather than guessed.' },
          { title: 'Temperature and output variability', body: 'Learn when variability is useful and when business workflows need constrained, structured outputs.' },
          { title: 'Structured outputs and schemas', body: 'Use predictable data contracts for downstream automation instead of parsing free-form text.' },
          { title: 'Failure modes engineers should expect', body: 'Hallucination, omission, overconfidence, stale knowledge, ambiguous instructions and unsafe tool use must be designed for.' },
        ],
        challenges: [
          'Rewrite a vague prompt into an instruction with role, task, context, constraints and expected output.',
          'Design a JSON response contract for an AI classifier that returns category, confidence, rationale and escalationRequired.',
          'List three cases where deterministic code should be preferred over an LLM call.',
        ],
      },
      {
        slug: 'prompt-engineering-testing',
        title: 'Prompt Engineering & Prompt Testing',
        level: 'Practical',
        duration: '90 min',
        summary: 'Treat prompts like production assets: version them, test them, compare them and defend them against regressions.',
        tags: ['Prompting', 'Evaluation', 'Regression'],
        outcomes: ['Create measurable prompt tests', 'Build prompt regression cases', 'Separate prompt quality from model quality'],
        lessons: [
          { title: 'Prompt design as specification', body: 'A production prompt is closer to executable policy than casual prose. Make inputs, constraints and output expectations explicit.' },
          { title: 'Golden datasets', body: 'Create representative examples with expected behaviour so prompt changes can be evaluated consistently.' },
          { title: 'Prompt regression testing', body: 'Compare new prompt versions against known cases, edge cases and adversarial inputs before release.' },
          { title: 'Scoring AI output', body: 'Combine exact checks, semantic criteria, rubric evaluation and human review depending on the workflow.' },
          { title: 'Prompt injection awareness', body: 'Treat retrieved and user-supplied content as untrusted input when instructions and tool access are involved.' },
        ],
        challenges: [
          'Create five regression test cases for a customer-enquiry classification prompt.',
          'Define pass/fail criteria for tone, factual grounding and escalation behaviour.',
          'Create one prompt-injection test and describe the expected safe response.',
        ],
      },
      {
        slug: 'rag-grounding',
        title: 'RAG, Grounding & Hallucination Control',
        level: 'Intermediate',
        duration: '90–120 min',
        summary: 'Learn how retrieval-augmented generation changes the quality problem and how to validate source-grounded answers.',
        tags: ['RAG', 'Embeddings', 'Grounding'],
        outcomes: ['Explain a RAG pipeline', 'Test retrieval quality', 'Design grounded-answer checks'],
        lessons: [
          { title: 'Why grounding matters', body: 'A model should not invent business facts that already exist in trusted systems or documents.' },
          { title: 'Retrieval pipeline basics', body: 'Chunking, embeddings, retrieval, ranking and context assembly all influence the final answer.' },
          { title: 'Retrieval quality vs answer quality', body: 'An answer can be wrong because the model reasoned poorly or because the right evidence was never retrieved.' },
          { title: 'Source attribution', body: 'Design responses so evidence can be traced and users can inspect the basis of important claims.' },
          { title: 'RAG test strategy', body: 'Test missing sources, conflicting sources, irrelevant retrieval, stale content and ambiguous queries.' },
        ],
        challenges: [
          'Design a RAG test matrix for an internal policy assistant.',
          'Define metrics for retrieval precision and grounded-answer quality.',
          'Write a safe fallback message for a query where no reliable source is retrieved.',
        ],
      },
      {
        slug: 'ai-governance-human-loop',
        title: 'AI Governance & Human-in-the-loop',
        level: 'Applied',
        duration: '90 min',
        summary: 'Turn confidence, risk, approval, auditability and fallback into concrete workflow controls.',
        tags: ['Governance', 'HITL', 'Risk'],
        outcomes: ['Define approval thresholds', 'Design audit evidence', 'Separate low-risk assistance from high-risk action'],
        lessons: [
          { title: 'Capability is not permission', body: 'An AI system being technically able to act does not mean the business should allow it to act autonomously.' },
          { title: 'Risk-tiering decisions', body: 'Classify actions by consequence, reversibility, regulatory sensitivity and customer impact.' },
          { title: 'Human approval patterns', body: 'Use review, edit, approve, reject and escalation patterns where confidence alone is insufficient.' },
          { title: 'Auditability', body: 'Capture context, prompt/version, output, confidence, user decision and final action so outcomes can be reconstructed.' },
          { title: 'Safe fallback', body: 'A mature workflow knows when to stop, escalate or ask for clarification instead of fabricating certainty.' },
        ],
        challenges: [
          'Create a three-tier risk model for AI-generated customer responses.',
          'Define when auto-send is allowed and when human approval is mandatory.',
          'List the minimum audit fields you would store for an AI-assisted business action.',
        ],
      },
    ],
  },
  {
    id: 'test-automation',
    title: 'Modern Test Automation',
    description: 'Build automation that is reliable, maintainable and useful in delivery pipelines rather than simply increasing script count.',
    icon: 'Code2',
    modules: [
      {
        slug: 'playwright-from-scratch',
        title: 'Playwright from Scratch',
        level: 'Beginner → Practical',
        duration: '2–3 hrs',
        summary: 'Learn browser automation through locators, assertions, fixtures, test data and debugging patterns.',
        tags: ['Playwright', 'TypeScript', 'UI'],
        outcomes: ['Write resilient UI tests', 'Use web-first assertions', 'Debug flaky automation'],
        lessons: [
          { title: 'Project setup and first test', body: 'Understand Playwright Test structure, configuration and how a test moves through arrange, act and assert.' },
          { title: 'Locators that survive UI change', body: 'Prefer role, label and test-id based locators over brittle CSS and XPath chains.' },
          { title: 'Web-first assertions', body: 'Let Playwright wait for observable conditions rather than adding arbitrary sleeps.' },
          { title: 'Fixtures and reusable setup', body: 'Share authentication, test data and environment setup without creating hidden coupling.' },
          { title: 'Debugging and traces', body: 'Use trace viewer, screenshots, videos and step-level evidence to diagnose failures quickly.' },
        ],
        challenges: [
          'Automate login using accessible locators and assert the authenticated state.',
          'Replace a fixed wait with a condition-based assertion.',
          'Create a reusable fixture for an authenticated user.',
        ],
      },
      {
        slug: 'automation-architecture',
        title: 'Automation Framework Architecture',
        level: 'Intermediate',
        duration: '90 min',
        summary: 'Design maintainable test automation using separation of concerns, services, fixtures and reusable business actions.',
        tags: ['Architecture', 'Patterns', 'Maintainability'],
        outcomes: ['Avoid giant page objects', 'Separate test intent from mechanics', 'Design reusable test services'],
        lessons: [
          { title: 'Tests should express business intent', body: 'A test should make the behaviour under validation obvious rather than expose every click and selector.' },
          { title: 'Page objects, components and services', body: 'Use abstraction where it reduces duplication without hiding important behaviour.' },
          { title: 'API setup for UI tests', body: 'Create state through APIs where possible so UI tests spend time validating UI behaviour rather than performing setup.' },
          { title: 'Test data ownership', body: 'Make test data deterministic, isolated and disposable to reduce flaky cross-test dependencies.' },
          { title: 'Parallel execution', body: 'Design tests so workers can run independently without fighting over shared users or records.' },
        ],
        challenges: [
          'Refactor a login-everywhere suite into a reusable authenticated fixture.',
          'Choose which setup steps belong in API helpers and which must remain UI actions.',
          'Design a folder structure for a Playwright suite with UI, API, fixtures and test data.',
        ],
      },
      {
        slug: 'flaky-test-engineering',
        title: 'Flaky Test Engineering',
        level: 'Practical',
        duration: '75 min',
        summary: 'Diagnose instability using timing, state, environment and data evidence instead of hiding failures with retries.',
        tags: ['Reliability', 'Debugging', 'CI'],
        outcomes: ['Classify flake causes', 'Use evidence to diagnose failures', 'Know when retries are appropriate'],
        lessons: [
          { title: 'What flakiness actually means', body: 'A flaky test produces inconsistent outcomes without a meaningful product change, usually because the test or environment is nondeterministic.' },
          { title: 'Timing and synchronization', body: 'Replace sleeps with observable conditions and understand eventual consistency where it genuinely exists.' },
          { title: 'Shared-state failures', body: 'Parallel tests often fail because they share accounts, records, queues or environment state.' },
          { title: 'Retries as evidence, not a cure', body: 'Retries can help classify transient problems but should not make unreliable tests appear healthy.' },
          { title: 'Flake dashboards', body: 'Track repeated offenders and failure signatures so teams fix systemic instability rather than triage the same noise repeatedly.' },
        ],
        challenges: [
          'Given a test that fails only in CI, list the evidence you would collect first.',
          'Replace a retry-based workaround with a deterministic waiting strategy.',
          'Design a simple flake metric for a regression suite.',
        ],
      },
    ],
  },
  {
    id: 'api-quality',
    title: 'API & Integration Quality',
    description: 'Test contracts, business rules, state changes, resilience and dependencies across distributed systems.',
    icon: 'Network',
    modules: [
      {
        slug: 'api-testing-beyond-200',
        title: 'API Testing Beyond HTTP 200',
        level: 'Practical',
        duration: '90 min',
        summary: 'Validate schemas, business invariants, negative paths, idempotency and downstream state instead of stopping at status codes.',
        tags: ['REST', 'Contracts', 'Negative Testing'],
        outcomes: ['Build API risk scenarios', 'Validate state transitions', 'Test meaningful negative paths'],
        lessons: [
          { title: 'Status code is only transport evidence', body: 'A 200 response says little about whether the correct business outcome occurred.' },
          { title: 'Schema and contract validation', body: 'Validate required fields, types, formats and compatibility because consumers depend on stable contracts.' },
          { title: 'Business invariants', body: 'Test rules that must remain true across every request, such as totals, permissions, ownership and lifecycle constraints.' },
          { title: 'Negative and boundary testing', body: 'Exercise malformed, missing, duplicated, unauthorised and out-of-range inputs intentionally.' },
          { title: 'State transitions and side effects', body: 'Validate databases, events, downstream APIs and retries where a request causes broader system change.' },
        ],
        challenges: [
          'Create a test matrix for POST /orders covering happy, negative, duplicate and authorization paths.',
          'Define a contract assertion that protects a mobile client from a breaking change.',
          'Identify what you would verify after a successful cancellation API call besides the HTTP response.',
        ],
      },
      {
        slug: 'contract-testing',
        title: 'Consumer Contract Testing',
        level: 'Intermediate',
        duration: '75 min',
        summary: 'Understand when consumer-driven contracts reduce integration risk and where they do not replace end-to-end testing.',
        tags: ['Contracts', 'Integration', 'Pact'],
        outcomes: ['Explain provider-consumer contracts', 'Identify breaking changes', 'Place contract tests in CI'],
        lessons: [
          { title: 'The integration problem', body: 'Distributed teams can deploy independently while accidentally changing assumptions relied on by consumers.' },
          { title: 'Consumer expectations', body: 'A contract captures the subset of provider behaviour that a specific consumer actually depends on.' },
          { title: 'Provider verification', body: 'Verify contracts against provider implementations before incompatible changes reach shared environments.' },
          { title: 'Versioning and compatibility', body: 'Use contracts to distinguish additive changes from changes that break existing consumers.' },
          { title: 'What contracts do not prove', body: 'They do not validate complete workflows, performance, infrastructure, data quality or real downstream availability.' },
        ],
        challenges: [
          'Describe a breaking vs non-breaking response change for a customer API.',
          'Choose where consumer and provider contract verification should run in CI.',
          'Explain one scenario that still requires an end-to-end integration test.',
        ],
      },
      {
        slug: 'integration-resilience-testing',
        title: 'Integration & Resilience Testing',
        level: 'Intermediate',
        duration: '90 min',
        summary: 'Test timeouts, retries, duplicate messages, partial failure and eventual consistency across integrated systems.',
        tags: ['Resilience', 'Events', 'Distributed Systems'],
        outcomes: ['Test partial failures', 'Validate idempotency', 'Reason about eventual consistency'],
        lessons: [
          { title: 'Distributed failure is normal', body: 'Dependencies can be slow, unavailable or inconsistent. Quality strategy must assume imperfect networks.' },
          { title: 'Timeouts and retries', body: 'Retries require bounded policies and idempotent operations or they can amplify incidents.' },
          { title: 'Duplicate events', body: 'Message delivery systems may redeliver. Consumers should avoid applying the same business effect twice.' },
          { title: 'Eventual consistency', body: 'Some workflows become correct over time rather than immediately, so assertions need clear convergence expectations.' },
          { title: 'Compensating actions', body: 'When multi-step workflows partially fail, systems may need rollback, reconciliation or manual recovery.' },
        ],
        challenges: [
          'Design a test for duplicate payment events.',
          'Define a bounded waiting strategy for an eventually consistent order status.',
          'Describe how you would test recovery after a downstream service times out after accepting a request.',
        ],
      },
    ],
  },
  {
    id: 'delivery-engineering',
    title: 'CI/CD, Observability & Release Engineering',
    description: 'Move from test execution to evidence-driven delivery using pipelines, telemetry, quality gates and production feedback.',
    icon: 'Activity',
    modules: [
      {
        slug: 'cicd-quality-gates',
        title: 'CI/CD Quality Gates',
        level: 'Practical',
        duration: '75 min',
        summary: 'Design fast feedback and meaningful release gates without turning pipelines into slow, noisy blockers.',
        tags: ['CI/CD', 'Pipelines', 'Risk'],
        outcomes: ['Layer tests by feedback speed', 'Design meaningful gates', 'Separate blocking vs informational signals'],
        lessons: [
          { title: 'Feedback economics', body: 'The earlier a defect is detected, the cheaper it is to diagnose, but not every test belongs in every pipeline stage.' },
          { title: 'Test pyramid in practice', body: 'Balance unit, service, integration and UI checks based on risk rather than chasing a fixed percentage.' },
          { title: 'Blocking quality gates', body: 'Block only on signals reliable enough to justify stopping delivery.' },
          { title: 'Quarantine and known instability', body: 'Unreliable tests should be visible and owned, not silently removed or allowed to poison confidence.' },
          { title: 'Release evidence', body: 'Combine test results, change risk, defects and operational readiness rather than reducing release decisions to one green tick.' },
        ],
        challenges: [
          'Design a pull-request pipeline and a pre-release pipeline with different test layers.',
          'Choose which failures should block deployment and justify why.',
          'Create a policy for quarantined flaky tests.',
        ],
      },
      {
        slug: 'observability-for-testers',
        title: 'Observability for Testers',
        level: 'Practical',
        duration: '75 min',
        summary: 'Use logs, metrics, traces and correlation IDs to test systems more intelligently and debug production behaviour faster.',
        tags: ['Logs', 'Metrics', 'Tracing'],
        outcomes: ['Use telemetry as test evidence', 'Trace requests across services', 'Define observable acceptance criteria'],
        lessons: [
          { title: 'Testing ends where observability begins', body: 'A test may prove one path in one environment. Production telemetry proves how systems behave under real load and data.' },
          { title: 'Logs with context', body: 'Useful logs include identifiers, state and outcomes rather than generic error text.' },
          { title: 'Metrics and service health', body: 'Latency, error rate, throughput and saturation show whether a release behaves safely at scale.' },
          { title: 'Distributed tracing', body: 'Trace IDs connect one business request across services and dependencies.' },
          { title: 'Observable requirements', body: 'Include telemetry expectations in design so failures can be diagnosed after deployment.' },
        ],
        challenges: [
          'Define logs and metrics for a customer checkout workflow.',
          'Create an acceptance criterion requiring correlation IDs across three services.',
          'List the production signals you would monitor after releasing a new payment integration.',
        ],
      },
    ],
  },
  {
    id: 'engineering-quality',
    title: 'Core Quality Engineering',
    description: 'Strengthen the judgement behind test design, risk analysis, requirements, data and non-functional quality.',
    icon: 'ShieldCheck',
    modules: [
      {
        slug: 'risk-based-test-design',
        title: 'Risk-Based Test Design',
        level: 'Foundation → Advanced',
        duration: '90 min',
        summary: 'Prioritise testing using likelihood, consequence, change complexity, usage and detectability instead of treating every requirement equally.',
        tags: ['Risk', 'Test Strategy', 'Coverage'],
        outcomes: ['Prioritise by business risk', 'Explain coverage decisions', 'Reduce low-value test volume'],
        lessons: [
          { title: 'Why equal coverage is weak strategy', body: 'Systems contain different consequences and failure probabilities, so testing effort should not be distributed evenly.' },
          { title: 'Risk dimensions', body: 'Consider customer impact, financial exposure, operational disruption, regulatory consequence and technical complexity.' },
          { title: 'Change-based risk', body: 'Recent code changes, integration touchpoints and architectural coupling can increase regression probability.' },
          { title: 'Coverage as evidence', body: 'Coverage is meaningful when it maps to risks and behaviours, not when it is merely a count of cases.' },
          { title: 'Exit decisions', body: 'Communicate residual risk clearly when time prevents exhaustive testing.' },
        ],
        challenges: [
          'Rank five checkout risks and decide where automation should focus first.',
          'Create a simple likelihood × impact model for release planning.',
          'Write a release note explaining an accepted residual testing risk.',
        ],
      },
      {
        slug: 'sql-data-validation',
        title: 'SQL & Data Validation for Testers',
        level: 'Foundation',
        duration: '2 hrs',
        summary: 'Use SQL to verify data state, joins, transformations, duplicates, nulls and business reconciliation.',
        tags: ['SQL', 'Data', 'Validation'],
        outcomes: ['Write useful SELECT queries', 'Validate joins and aggregates', 'Detect data-quality problems'],
        lessons: [
          { title: 'SELECT, WHERE and ORDER BY', body: 'Retrieve precise evidence instead of relying only on what the UI displays.' },
          { title: 'JOINs', body: 'Validate relationships between orders, customers, payments and other linked business entities.' },
          { title: 'Aggregations', body: 'Use COUNT, SUM and GROUP BY for reconciliation and anomaly detection.' },
          { title: 'NULLs and duplicates', body: 'Missing and duplicate data often reveal integration and migration problems.' },
          { title: 'Data validation patterns', body: 'Compare source and target counts, totals, transformations and referential integrity.' },
        ],
        challenges: [
          'Write a query to find duplicate customer emails.',
          'Write a reconciliation query comparing order totals with payment totals.',
          'Identify orphan records where child rows no longer have a valid parent.',
        ],
      },
      {
        slug: 'accessibility-testing',
        title: 'Accessibility Testing Essentials',
        level: 'Foundation',
        duration: '60 min',
        summary: 'Build accessible quality checks into normal delivery using keyboard, semantics, labels, contrast awareness and automated scanning.',
        tags: ['Accessibility', 'WCAG', 'UI'],
        outcomes: ['Run basic accessibility checks', 'Recognise semantic issues', 'Combine automation with manual testing'],
        lessons: [
          { title: 'Accessibility is product quality', body: 'A feature that cannot be used by part of the audience is functionally incomplete.' },
          { title: 'Keyboard navigation', body: 'Core workflows should be usable without a mouse and focus order should remain logical.' },
          { title: 'Semantic HTML and labels', body: 'Assistive technologies rely on meaningful roles, labels and relationships.' },
          { title: 'Automated checks', body: 'Tools catch a useful subset of issues but cannot determine whether an experience is genuinely usable.' },
          { title: 'Manual accessibility heuristics', body: 'Combine keyboard, zoom, screen-reader awareness and content clarity with automated scanning.' },
        ],
        challenges: [
          'Test a login form using keyboard only.',
          'Identify three accessibility problems that automated tools may miss.',
          'Create an accessibility acceptance checklist for a modal dialog.',
        ],
      },
      {
        slug: 'performance-testing-basics',
        title: 'Performance Testing Basics',
        level: 'Foundation',
        duration: '75 min',
        summary: 'Understand load, stress, soak, latency percentiles and the system evidence needed before performance testing becomes useful.',
        tags: ['Performance', 'Load', 'Scalability'],
        outcomes: ['Choose the right performance test', 'Read percentile latency', 'Define workload models'],
        lessons: [
          { title: 'Performance is a requirement', body: 'Without expected user volume, transaction mix and response targets, performance tests produce numbers without meaning.' },
          { title: 'Load vs stress vs soak', body: 'Different test types answer different questions about capacity, breaking points and degradation over time.' },
          { title: 'Percentiles', body: 'Average latency hides slow experiences. P95 and P99 show how the slower portion of requests behaves.' },
          { title: 'Workload modelling', body: 'Represent realistic concurrency, think time and transaction distribution rather than generating arbitrary traffic.' },
          { title: 'Server-side evidence', body: 'CPU, memory, database, queues and dependency timing are needed to explain why performance changes.' },
        ],
        challenges: [
          'Define a workload model for an event ticket sale opening at 9:00 AM.',
          'Explain why average response time alone is misleading.',
          'Choose metrics you would monitor during a soak test.',
        ],
      },
    ],
  },
  {
    id: 'agentic-future',
    title: 'Agents, MCP & Future-ready Engineering',
    description: 'Understand how AI moves from answering questions to invoking tools, and what engineering controls are needed when systems can act.',
    icon: 'Cpu',
    modules: [
      {
        slug: 'mcp-for-engineers',
        title: 'MCP for Engineers',
        level: 'Intermediate',
        duration: '90 min',
        summary: 'Understand Model Context Protocol concepts, tool boundaries, schemas, permissions and testing considerations.',
        tags: ['MCP', 'Tools', 'AI Architecture'],
        outcomes: ['Explain MCP tools and resources', 'Design tool schemas', 'Test permission boundaries'],
        lessons: [
          { title: 'Why tools matter', body: 'LLMs become more useful when they can access explicit capabilities instead of guessing or relying entirely on prompt context.' },
          { title: 'Tool contracts', body: 'Inputs and outputs should be strongly typed, bounded and understandable so agents cannot improvise unsafe parameters.' },
          { title: 'Permissions and least privilege', body: 'Expose only the capabilities necessary for a workflow and distinguish read actions from high-impact writes.' },
          { title: 'Human approval around tools', body: 'Sensitive actions may require confirmation even when the agent selected the correct tool.' },
          { title: 'Testing MCP tools', body: 'Validate schema errors, authorization, duplicate execution, unsafe arguments and audit evidence.' },
        ],
        challenges: [
          'Design an MCP tool schema for create_event with required validation.',
          'Classify search_event, update_event and issue_refund by risk level.',
          'Create three negative tests for a tool that can send customer messages.',
        ],
      },
      {
        slug: 'agentic-ai-testing',
        title: 'Testing Agentic AI',
        level: 'Advanced',
        duration: '2 hrs',
        summary: 'Test plans, tool selection, loops, permissions, side effects and recovery when AI can perform multi-step actions.',
        tags: ['Agents', 'Evaluation', 'Safety'],
        outcomes: ['Test agent behaviour', 'Detect unsafe loops', 'Validate tool-use boundaries'],
        lessons: [
          { title: 'Agents are workflows with autonomy', body: 'Testing must consider not just final text but intermediate plans, tool calls, retries and side effects.' },
          { title: 'Tool-selection accuracy', body: 'A correct answer produced through the wrong or overly privileged tool can still be an unsafe result.' },
          { title: 'Loop and retry controls', body: 'Agents need bounded attempts and recovery behaviour to avoid runaway cost or repeated side effects.' },
          { title: 'Permission boundary testing', body: 'Test whether the agent refuses actions outside the user, workspace or role permissions.' },
          { title: 'End-to-end agent evaluation', body: 'Measure task success, safety, tool correctness, cost, latency and human intervention rate together.' },
        ],
        challenges: [
          'Design a test where an agent attempts to update another user’s record.',
          'Create a failure scenario where a tool times out after performing the action.',
          'Define five metrics for an agentic customer-support workflow.',
        ],
      },
    ],
  },
]

export const ALL_MODULES = LEARNING_TRACKS.flatMap((track) =>
  track.modules.map((module) => ({ ...module, trackId: track.id, trackTitle: track.title }))
)

export function getLearningModule(slug) {
  return ALL_MODULES.find((module) => module.slug === slug)
}
