import {
  ClipboardCheck, FileCheck2, ShieldAlert, GitBranch, Target, FlaskConical,
  Bug, Database, Gauge, Rocket, Braces, Table2, WandSparkles, ScanSearch,
  Network, FileSearch, ListChecks, Workflow,
} from 'lucide-react'

export const TOOL_GROUPS = [
  { id: 'core-qa', label: 'Core QA', description: 'Turn requirements into practical testing assets.' },
  { id: 'risk-quality', label: 'Risk & Quality', description: 'Find gaps, risk and release concerns before they become defects.' },
  { id: 'automation-data', label: 'Automation & Data', description: 'Identify automation value and build stronger technical test coverage.' },
]

export const QA_TOOLS = [
  {
    slug: 'requirement-to-test-cases', group: 'core-qa', icon: ClipboardCheck,
    title: 'Requirement → Test Cases', shortTitle: 'Test Case Generator',
    description: 'Upload or paste a requirement, user story or BRD and generate detailed positive, negative, boundary and exception test cases.',
    badge: 'Most useful', inputLabel: 'Requirement / user story / BRD',
    output: 'Test cases with IDs, preconditions, steps, expected results, priority and test type.',
    prompt: `Act as a senior QA test analyst. Convert the supplied requirement into executable test cases. Cover happy path, negative, validation, boundary, error handling, permissions, integration, data integrity, usability, recovery and relevant non-functional risks. Do not invent business rules without labelling them as assumptions. Use clear IDs (TC-001...), preconditions, test data, numbered steps, expected result, priority, test type, requirement reference and automation suitability. Finish with assumptions and unanswered questions.`,
  },
  {
    slug: 'test-plan-generator', group: 'core-qa', icon: FileCheck2,
    title: 'Test Plan Generator', shortTitle: 'Test Plan',
    description: 'Create a practical test plan from a requirement, project brief, release scope or solution document.',
    badge: 'QA Lead', inputLabel: 'Project scope / requirements / solution document',
    output: 'Scope, approach, environments, entry/exit criteria, risks, roles, schedule, reporting and sign-off.',
    prompt: `Act as an experienced Test Manager. Create a project-ready test plan grounded only in the supplied material. Include objectives, in-scope, out-of-scope, assumptions, test levels/types, environments, test data, roles and responsibilities, entry criteria, exit criteria, defect management, regression approach, automation approach, non-functional testing, dependencies, risks/mitigations, reporting metrics, milestones, evidence/sign-off and open decisions. Explicitly mark anything not supported by the source as TBD rather than inventing it.`,
  },
  {
    slug: 'acceptance-criteria-generator', group: 'core-qa', icon: ListChecks,
    title: 'Acceptance Criteria Generator', shortTitle: 'Acceptance Criteria',
    description: 'Turn rough requirements into testable acceptance criteria and flag ambiguity before development starts.',
    inputLabel: 'Requirement / feature idea / user story',
    output: 'Testable criteria, Given/When/Then scenarios, assumptions and questions.',
    prompt: `Act as a senior BA and QA lead. Rewrite the supplied feature into precise, testable acceptance criteria. Include business rules, validations, negative paths, permissions and error outcomes where supported. Provide concise Given/When/Then scenarios. Flag ambiguous or missing information as questions instead of guessing.`,
  },
  {
    slug: 'requirements-quality-checker', group: 'risk-quality', icon: ScanSearch,
    title: 'Requirements Quality Checker', shortTitle: 'Requirement Review',
    description: 'Find ambiguity, contradictions, missing rules, untestable statements and hidden dependencies before testing begins.',
    badge: 'Shift left', inputLabel: 'Requirement / BRD / user story',
    output: 'Quality score, findings by severity, ambiguity list, missing information and recommended rewrite.',
    prompt: `Review the supplied requirements as a senior QA/BA reviewer. Assess clarity, completeness, consistency, testability, traceability, measurable outcomes, business rules, validation, permissions, error handling, data rules, dependencies and non-functional needs. Give a 0-100 quality score with rationale. List Critical/High/Medium/Low findings, exact problematic wording where possible, why it matters, recommended clarification, and questions for the product owner. Never fabricate missing requirements.`,
  },
  {
    slug: 'risk-based-test-analysis', group: 'risk-quality', icon: ShieldAlert,
    title: 'Risk-Based Test Analysis', shortTitle: 'Risk Analysis',
    description: 'Prioritise testing using business impact, likelihood, complexity, change size and detectability.',
    inputLabel: 'Change / release / feature scope',
    output: 'Risk matrix, priority test areas, reduced-scope recommendation and residual risks.',
    prompt: `Act as a risk-based testing specialist. Identify product and delivery risks from the supplied scope. For each risk provide cause, affected area, likelihood 1-5, impact 1-5, risk score, priority, proposed test coverage, mitigation and residual risk. Separate business, integration, data, security, operational and regression risks. Finish with a recommended test execution order and what must not be cut if schedule is compressed.`,
  },
  {
    slug: 'traceability-matrix-generator', group: 'core-qa', icon: GitBranch,
    title: 'Traceability Matrix Generator', shortTitle: 'RTM Generator',
    description: 'Map requirements to acceptance criteria and tests, exposing missing or duplicate coverage.',
    inputLabel: 'Requirements and/or existing test cases',
    output: 'RTM table with requirement IDs, coverage status, test references and gaps.',
    prompt: `Create a requirements traceability matrix from the supplied material. Preserve source requirement IDs when present. Map requirement -> acceptance criteria -> test scenarios/test cases. Mark coverage as Covered, Partial, Missing or Duplicate. Identify orphan test cases and untested requirements. If IDs do not exist, create neutral derived IDs and clearly state they are generated.`,
  },
  {
    slug: 'boundary-value-generator', group: 'core-qa', icon: Target,
    title: 'Boundary & Equivalence Test Generator', shortTitle: 'Boundary Tests',
    description: 'Generate BVA, equivalence partitions, invalid partitions and edge cases for fields and business rules.',
    inputLabel: 'Field rules / validations / requirement',
    output: 'Boundary table, partitions, representative values and expected outcomes.',
    prompt: `Act as a specialist in test design techniques. Identify numeric, date, length, range, enum and state constraints from the input. Generate equivalence partitions and boundary values including just-below, minimum, just-above-minimum, nominal, just-below-maximum, maximum and just-above-maximum where meaningful. Include invalid/null/empty/special-character/time-zone/rounding cases when relevant. Do not invent limits that are not in the source; flag them as missing.`,
  },
  {
    slug: 'exploratory-test-charter', group: 'core-qa', icon: FlaskConical,
    title: 'Exploratory Testing Charter', shortTitle: 'Exploratory Charter',
    description: 'Create focused exploratory sessions with mission, heuristics, test ideas, data and evidence prompts.',
    inputLabel: 'Feature / change description',
    output: 'Time-boxed charters, personas, tours, heuristics, test data and observation checklist.',
    prompt: `Create practical exploratory testing charters for the supplied feature. Each charter must include mission, scope, timebox, risks targeted, setup/test data, heuristics/tours, concrete test ideas, observations to capture and stopping criteria. Include at least one abuse/error-recovery charter and one integration/data charter where relevant.`,
  },
  {
    slug: 'defect-report-improver', group: 'core-qa', icon: Bug,
    title: 'Defect Report Improver', shortTitle: 'Defect Improver',
    description: 'Turn rough bug notes into a developer-ready defect with reproducible steps, evidence checklist and severity rationale.',
    inputLabel: 'Raw defect notes / observed behaviour',
    output: 'Clear title, environment, preconditions, steps, actual/expected, impact, severity and evidence needed.',
    prompt: `Act as a senior QA defect triager. Rewrite the supplied defect notes into a concise, reproducible engineering defect. Include title, environment, build/version if supplied, preconditions, data, numbered steps, actual result, expected result, frequency, business/user impact, suggested severity and priority with rationale, evidence checklist, likely affected areas (not speculative root cause), and follow-up questions. Never invent evidence.`,
  },
  {
    slug: 'test-data-generator', group: 'automation-data', icon: Database,
    title: 'Test Data Designer', shortTitle: 'Test Data',
    description: 'Design representative positive, negative, boundary, privacy-safe and combinatorial test data.',
    inputLabel: 'Data rules / schema / requirement',
    output: 'Test data matrix with purpose, values, expected validity and masking/privacy notes.',
    prompt: `Design a comprehensive test-data set based on the supplied rules. Include valid, invalid, boundary, null/empty, duplicate, special character, locale/time-zone, high-volume and referential-integrity cases where relevant. Use synthetic values only. Never generate real credentials, personal data or secrets. Present a clear table with data item, value/example, purpose, expected validity and notes.`,
  },
  {
    slug: 'regression-impact-analyser', group: 'risk-quality', icon: Network,
    title: 'Regression Impact Analyser', shortTitle: 'Regression Impact',
    description: 'Analyse a change and identify direct, upstream, downstream, integration and data regression areas.',
    inputLabel: 'Change request / technical design / release notes',
    output: 'Impact map, regression scope, prioritised suite, dependencies and smoke recommendation.',
    prompt: `Act as a regression test lead. Analyse the supplied change for direct and indirect regression impact. Identify changed components, upstream/downstream dependencies, APIs, data flows, permissions, integrations, reports, batch jobs and operational processes where supported. Provide Must Test / Should Test / Nice to Test scope, smoke tests, targeted regression, full-regression triggers and explicit unknowns.`,
  },
  {
    slug: 'release-readiness-assessment', group: 'risk-quality', icon: Rocket,
    title: 'Release Readiness Assessment', shortTitle: 'Release Readiness',
    description: 'Turn test status, defects and outstanding risks into a clear release recommendation with conditions.',
    inputLabel: 'Test summary / defects / known risks / release status',
    output: 'Go / Conditional Go / No-Go recommendation, evidence, blockers, residual risk and actions.',
    prompt: `Act as a Test Manager preparing a release-readiness recommendation. Based only on supplied evidence, assess functional coverage, regression, defect status, critical business flows, non-functional evidence, environments/data, deployment/rollback readiness and residual risk. Output GO, CONDITIONAL GO or NO-GO with rationale, blockers, conditions, accepted risks, missing evidence and immediate next actions. Do not infer tests passed unless evidence says so.`,
  },
  {
    slug: 'api-test-scenario-generator', group: 'automation-data', icon: Braces,
    title: 'API Test Scenario Generator', shortTitle: 'API Tests',
    description: 'Generate functional, negative, contract, auth, idempotency, pagination and resilience scenarios from an API spec or description.',
    inputLabel: 'API contract / endpoint description / OpenAPI excerpt',
    output: 'Endpoint test matrix including request, expected response, validation and automation priority.',
    prompt: `Act as a senior API test engineer. Generate API scenarios from the supplied contract. Cover success, required/optional fields, schema validation, type/format, auth/authz, invalid tokens, permissions, status codes, error contract, idempotency, duplicate requests, pagination/filter/sort, concurrency, rate limits, timeouts/retries, downstream failures, data persistence and security-relevant input handling where applicable. Clearly separate supported rules from assumptions.`,
  },
  {
    slug: 'data-validation-checklist', group: 'automation-data', icon: Table2,
    title: 'Data Validation & SQL Test Checklist', shortTitle: 'Data Validation',
    description: 'Create database and data-pipeline validation scenarios for migrations, interfaces, ETL and transactional systems.',
    inputLabel: 'Data mapping / schema / migration or interface scope',
    output: 'Source-target checks, integrity rules, reconciliation tests, SQL ideas and failure scenarios.',
    prompt: `Act as a data QA specialist. Produce a data validation checklist for the supplied mapping or flow. Cover row counts, duplicates, nulls, keys, referential integrity, data types, precision/scale, transformations, defaults, timestamps/time zones, incremental loads, reruns/idempotency, reconciliation, rejected records, audit fields, performance and rollback. Include example generic SQL patterns only where they can be written without inventing table or column names.`,
  },
  {
    slug: 'automation-candidate-analyser', group: 'automation-data', icon: WandSparkles,
    title: 'Automation Candidate Analyser', shortTitle: 'Automation Fit',
    description: 'Score manual test cases for automation value, stability, complexity and maintenance cost.',
    inputLabel: 'Manual test cases / regression suite',
    output: 'Automation score, recommended layer, ROI rationale, blockers and implementation order.',
    prompt: `Act as a test automation architect. Assess the supplied test cases for automation suitability. Score business value, execution frequency, stability, determinism, data/setup complexity, integration dependencies, maintenance cost and flakiness risk. Recommend Automate Now / Automate Later / Keep Manual and the best layer (unit/API/UI/component/data) with rationale. Prioritise ROI and reliability, not automation percentage.`,
  },
  {
    slug: 'test-strategy-reviewer', group: 'risk-quality', icon: FileSearch,
    title: 'Test Strategy Reviewer', shortTitle: 'Strategy Review',
    description: 'Review an existing test plan or strategy and identify what a senior Test Manager would challenge before sign-off.',
    inputLabel: 'Existing test plan / strategy',
    output: 'Strengths, gaps, risks, missing evidence, governance concerns and recommended improvements.',
    prompt: `Review the supplied test strategy as a senior Test Manager. Challenge scope, risk alignment, environments, test data, integration coverage, non-functional coverage, automation, regression, entry/exit criteria, defect workflow, evidence, metrics, roles, schedule realism, dependencies, release governance and rollback. Separate critical gaps from improvements and provide concrete remediation actions.`,
  },
  {
    slug: 'end-to-end-flow-designer', group: 'core-qa', icon: Workflow,
    title: 'End-to-End Test Flow Designer', shortTitle: 'E2E Flow',
    description: 'Convert a multi-system business workflow into end-to-end scenarios, checkpoints and ownership boundaries.',
    inputLabel: 'Business process / system flow / integration description',
    output: 'E2E scenarios, system hops, checkpoints, data hand-offs, failure points and evidence requirements.',
    prompt: `Act as an enterprise end-to-end test lead. Convert the supplied business process into end-to-end test flows. Identify actors, systems, hand-offs, input/output data, checkpoints, integration assertions, downstream consequences, exception/recovery flows and evidence at each hop. Highlight ownership boundaries and where defects may be misattributed between systems.`,
  },
]

export function getTool(slug) {
  return QA_TOOLS.find((tool) => tool.slug === slug)
}
